### ISSUE TITLE
Kyber Network Integration Bounty: Prize of 3000 USD in KNC

### ISSUE THREAD

**Issue by ayobuenavista** [ethberlin-hackathon/ETHBerlin-Bounties#39]
# Build with Kyber Network's Liquidity Protocol

[Kyber](https://kyber.network/) is building the decentralized liquidity protocol that allows open contribution of liquidity from token holders. Our Developer Platform enables a whole new class of decentralized applications, including payments in multiple tokens.

https://developer.kyber.network/docs/VendorsUseCase
https://developer.kyber.network/docs/DappsUseCase
https://developer.kyber.network/docs/WalletsUseCase

## Ideas
Some hints for integration you might work on:

### [DApp Integration](https://developer.kyber.network/docs/DappsGuide): 

Directly integrate with Kyber Network's smart contracts to your DApp

### [Swap Widget](https://developer.kyber.network/docs/WidgetOverview): 

Provide token swap service inside your application/website

### [Buy token widget](https://developer.kyber.network/docs/WidgetOverview): 

Allow your users to buy/swap tokens without leaving your website

### [Payment widget](https://developer.kyber.network/docs/WidgetOverview): 

Allow users to pay for goods, services, etc. in any token they want, and you will receive the token of your choice

## Bounty

Integrating Kyber Network's protocol for your application/website/DApp for whatever use case will be considered for this bounty. The prize will be 3000 USD worth of KNC tokens.

### Community
All members of your team should join our [telegram developer group](https://t.me/KyberDeveloper). Our developer community there will be happy to help.

### Submission: 

Your GitHub repo, demo video, or live website will be preferred.

## Resources

You can find all resources from our [developer portal](https://developer.kyber.network//)

**Comment by casparschwa** [comment]
Closing this issue because this sponsor prize is not part of the official ETHBerlin track.
